CREATE TABLE todos (
  id SERIAL PRIMARY KEY,
  creator_name VARCHAR(100) NOT NULL,
  title VARCHAR(256) NOT NULL,
  description VARCHAR(1000) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);